  - job_name: 'kubernetes-kubelet'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/ca.crt
    bearer_token_file: /etc/prometheus/token
    kubernetes_sd_configs:
    - api_server: https://cluster.kube.com:16443
      role: node
      bearer_token_file: /etc/prometheus/token
      tls_config:
        ca_file: /etc/prometheus/ca.crt
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: cluster.kube.com:16443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics
  - job_name: 'kubernetes-cadvisor'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/ca.crt
    bearer_token_file: /etc/prometheus/token
    kubernetes_sd_configs:
    - role: node
      api_server: https://cluster.kube.com:16443
      bearer_token_file: /etc/prometheus/token
      tls_config:
        ca_file: /etc/prometheus/ca.crt
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: cluster.kube.com:16443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
  - job_name: 'kubernetes-kube-state'
    kubernetes_sd_configs:
    - api_server: https://cluster.kube.com:16443
      role: pod
      bearer_token_file: /etc/prometheus/token
      tls_config:
        ca_file: /etc/prometheus/ca.crt
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
    - source_labels: [__meta_kubernetes_pod_label_grafanak8sapp]
      regex: .*true.*
      action: keep
    - source_labels: ['__meta_kubernetes_pod_label_daemon', '__meta_kubernetes_pod_node_name']
      regex: 'node-exporter;(.*)'
      action: replace
      target_label: nodename